### ISSUE TITLE
Use newer version of ESP-IDF as required IDF version for better ESP32-C6 and ESP32-H2 support?

### ISSUE THREAD

**Issue by Hedda** [luar123/esphome_zb_sensor#1]
Suggest set a higher minimum requirement for ESP-IDF version since 5.0.0 does not have "good" support for ESP32-C6/ESP32-H2?

ESP-IDF v5.0.0 was first version to support ESP32-C6 and ESP32-H2, but they do not have "good" support until ESP-IDF v5.1 or 5.2

**Comment by luar123** [comment]
Not sure what exactly you are talking about. In ZB_sensor.yaml the esp-idf version is set to 5.1.2.

**Comment by lboue** [comment]
> Not sure what exactly you are talking about. In ZB_sensor.yaml the esp-idf version is set to 5.1.2.

@luar123 
Here:
https://github.com/luar123/esphome_zb_sensor/blob/master/idf_component.yml#L8

**Comment by luar123** [comment]
Yes, could be changed to 5.1. Just took this file from the example.

**Comment by Hedda** [comment]
> Here:
> https://github.com/luar123/esphome_zb_sensor/blob/master/idf_component.yml#L8

Yeah that is what I meant. There is currently require 5.0.0 or newer

**Comment by lboue** [comment]
I made PR #8 for that.
