### ISSUE TITLE
Question about allowing to build for both ESP32-H2 and ESP32-C6

### ISSUE THREAD

**Issue by lboue** [luar123/esphome_zb_sensor#15]
Hello,

What do you recommend to enable compilation for both ESP32-H2 and ESP32-C6?
Would we need 2 different YAML files, one for each type?

**Comment by luar123** [comment]
Yes, you need a new yaml for C6. Just copy it and replace variant and board. Probably you could also remove the platform key for C6.

**Comment by lboue** [comment]
> Yes, you need a new yaml for C6. Just copy it and replace variant and board. Probably you could also remove the platform key for C6.

@luar123 
It works with this one: [ZB_C6_sensor.yaml](https://github.com/lboue/esphome_zb_sensor/blob/ZB_C6_sensor/ZB_C6_sensor.yaml).
