### ISSUE TITLE
How to add light or switch?

### ISSUE THREAD

**Issue by dronix27** [luar123/esphome_zb_sensor#26]
I added a switch cluster, but I don't know how to send a command to switch. Here is my configuration.
In _esp_zb_light.c_
// ------------------------------ Cluster Light ------------------------------
    esp_zb_on_off_cluster_cfg_t on_off_cluster_cfg = {
        .on_off = 0,
    };
    esp_zb_attribute_list_t *esp_zb_on_off_cluster = esp_zb_on_off_cluster_create(&on_off_cluster_cfg);

In _ZB_sensor.yaml_
light:
  - platform: esp32_rmt_led_strip
    rmt_channel: 0
    chipset: WS2812
    rgb_order: GRB
    pin: GPIO8
    num_leds: 1
    name: "Status LED"
    id: internal_led

**Comment by luar123** [comment]
Have a look at the SDK examples: https://github.com/espressif/esp-zigbee-sdk/tree/main/examples/esp_zigbee_HA_sample

There is already some code in the attribute handler to toggle a light, however, you need to call the actions of your light object. Not sure how to do that easily. Maybe you have to create a function to register a callback. I have not looked into that.

**Comment by luar123** [comment]
See https://github.com/luar123/zigbee_esphome/blob/master/example_esp32h2.yaml for a working implementation.
